# config.py

# Channel 
#ENTER YOUR TELEGRAM CHANNEL TO PROMOTE WHEN BOT STARTED OR USED HELP 
#BY DEFAULT DEVELOPER CHANNEL IS GIVEN
CHANNEL_LINK = "https://t.me/py_hubs"

#ENTER G-DRIVE PUBLIC IMAGE URL CONVERT THAT IN THIS FORM /USE CHATGPT BRO
#IN THIS FORMAT= "https://drive.google.com/uc?export=view&id=1KBGv6683FnQC96oSfKCYOv3lt3WFopwI"
IMAGE_URL = "ENTER G-DRIVE START PFP URL"

#ENTER ADMIN ID/IDs
ADMIN_ID = [1234567890]

#ENTER A PRIVATE CHANNEL ID WHERE ALL LOGS WERE SENT 
# #IN THIS FORMAT=-1001234560789 
NOTIFY_CHANNEL = int["ENTER CHANNEL URL"]

#ENTER YOUR USERNAME WITHOUT @
telegram_username = "socialxspy"

owner = f"https://t.me/{telegram_username}"

#Enter your telegram token obtain by Bot father:
TG_TOKEN="Telegram token"


#ENTER bOT USERNAME WITH @:
BOT_USERNAME="BOT USERNAME"
